services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file: config.env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    stop_grace_period: 15s
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5

  migrate:
    image: golang:1.23
    container_name: migrate
    env_file: config.env
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    command: >
      /bin/sh -c "
      go install github.com/pressly/goose/v3/cmd/goose@latest &&
      goose -dir ./migrations postgres \"user=$${POSTGRES_USER} password=$${POSTGRES_PASSWORD} host=$${POSTGRES_HOST} sslmode=disable dbname=$${POSTGRES_DB}\" up
      "

  app:
    build: .
    container_name: app
    env_file: config.env
    volumes:
      - ./config.env:/app/config.env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    stop_grace_period: 5s

volumes:
  db-data: